#配置Mybatis-Plus
mybatis-plus:
  #配置扫描xml
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  #配置实体扫描类
  type-aliases-package: com.demo.mapper.*.mapper
  #逻辑删除配置
  global-config:
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-delete-value: 1
    logic-not-delete-value: 0

