# Redis数据库索引（默认为0）
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    location: banner.txt

jasypt:
  encryptor:
    password: 123456



