spring:
  servlet:
    multipart:
      max‐file‐size: 10MB
      max‐request‐size: 10MB
server:
  port: 8003
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:8001/eureka
  instance:
    prefer‐ip‐address: true
feign:
  hystrix:
    enabled: true
